### ISSUE TITLE
Digital Object Identifiers (DOI) for Splint

### ISSUE THREAD

**Issue by oxr463** [splintchecker/splint#15]
I'd like to cite Splint in an academic setting.

See: https://guides.github.com/activities/citable-code

**Comment by evansuva** [comment]
Is there a reason you prefer to site a repository instead of a paper or the reference manual? 

There are several splint papers, see https://splint.org/pubs.html. It is usually more appropriate to cite one of these than to cite code, unless there is something specific about the implementation you need to reference.

**Comment by oxr463** [comment]
None at all. That will do nicely, thanks!
